<a href="https://colab.research.google.com/github/Sonu2252/Abhi/blob/master/BERT_Embedding_Extracting_Sentiment_Q%26A_pynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install transformers==3.5.1

     |████████████████████████████████| 1.3 MB 5.0 MB/s 
     |████████████████████████████████| 2.9 MB 35.6 MB/s 
     |████████████████████████████████| 1.1 MB 31.7 MB/s 
     |████████████████████████████████| 880 kB 46.9 MB/s 
  Created wheel for sacremoses: filename=sacremoses-0.0.53-py3-none-any.whl size=895260 sha256=56c05f4587f704ba7fec224881c078fb4dd60b816466dadd374ad1d53c3d02e3
  Stored in directory: /root/.cache/pip/wheels/87/39/dd/a83eeef36d0bf98e7a4d1933a4ad2d660295a40613079bafc9
Successfully built sacremoses


In [2]:
!pip install torch==1.4.0

     |████████████████████████████████| 753.4 MB 4.8 kB/s 
  Attempting uninstall: torch
    Found existing installation: torch 1.11.0+cu113
    Uninstalling torch-1.11.0+cu113:
      Successfully uninstalled torch-1.11.0+cu113
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchvision 0.12.0+cu113 requires torch==1.11.0, but you have torch 1.4.0 which is incompatible.
torchtext 0.12.0 requires torch==1.11.0, but you have torch 1.4.0 which is incompatible.
torchaudio 0.11.0+cu113 requires torch==1.11.0, but you have torch 1.4.0 which is incompatible.


In [3]:
import torch

In [4]:
from transformers import BertModel, BertTokenizer


In [5]:
model = BertModel.from_pretrained('bert-base-uncased')

Downloading:   0%|          | 0.00/570 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/440M [00:00<?, ?B/s]

In [6]:
model

BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(30522, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0): BertLayer(
        (attention): BertAttention(
          (self): BertSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          

In [7]:
tokenizer=BertTokenizer.from_pretrained('bert-base-uncased')

Downloading:   0%|          | 0.00/232k [00:00<?, ?B/s]

In [8]:
sentence = 'I love Pizza'
tokens = tokenizer.tokenize(sentence)

In [9]:
print(tokens)

['i', 'love', 'pizza']


In [10]:
tokens = ['[CLS]'] + tokens + ['[SEP]']

In [11]:
print(tokens)

['[CLS]', 'i', 'love', 'pizza', '[SEP]']


In [12]:
tokens = tokens + ['[PAD]'] + ['[PAD]']

In [13]:
print(tokens)

['[CLS]', 'i', 'love', 'pizza', '[SEP]', '[PAD]', '[PAD]']


In [14]:
attention_mask = [1 if i!= '[PAD]' else 0 for i in tokens]

In [15]:
print(attention_mask)

[1, 1, 1, 1, 1, 0, 0]


In [16]:
token_ids = tokenizer.convert_tokens_to_ids(tokens)

In [17]:
print(token_ids)

[101, 1045, 2293, 10733, 102, 0, 0]


In [18]:
token_ids = torch.tensor(token_ids).unsqueeze(0)
attention_mask = torch.tensor(attention_mask).unsqueeze(0)

In [19]:
token_ids

tensor([[  101,  1045,  2293, 10733,   102,     0,     0]])

In [20]:
attention_mask

tensor([[1, 1, 1, 1, 1, 0, 0]])

In [21]:
hidden_rep, cls_head = model(token_ids, attention_mask = attention_mask)

In [22]:
print(hidden_rep.shape)

torch.Size([1, 7, 768])


In [23]:
print(cls_head.shape)

torch.Size([1, 768])


In [24]:
hidden_rep

tensor([[[ 0.1382,  0.3043,  0.0631,  ..., -0.1041,  0.2224,  0.1510],
         [ 0.3200,  0.2953, -0.1416,  ..., -0.2075,  0.8356,  0.2033],
         [ 1.1893,  0.6508,  0.6801,  ...,  0.1086,  0.4138, -0.2404],
         ...,
         [ 0.6175,  0.1778, -0.0403,  ...,  0.0127, -0.5838, -0.3406],
         [ 0.1496,  0.2934,  0.2243,  ...,  0.2741,  0.2030,  0.0692],
         [ 0.0636,  0.0767,  0.2692,  ...,  0.3536,  0.1529,  0.0537]]],
       grad_fn=<NativeLayerNormBackward>)

In [25]:
cls_head

tensor([[-8.2725e-01, -2.3180e-01,  4.3839e-01,  5.4852e-01, -1.2203e-01,
         -1.3028e-01,  8.1214e-01,  1.7054e-01,  1.3439e-01, -9.9966e-01,
          1.5789e-01,  2.2010e-01,  9.7317e-01, -2.6980e-01,  9.1344e-01,
         -4.1248e-01,  6.5047e-02, -4.9485e-01,  3.1212e-01, -5.5773e-01,
          5.3245e-01,  8.3556e-01,  5.6662e-01,  2.2098e-01,  3.7355e-01,
          3.8081e-01, -5.0410e-01,  8.9866e-01,  9.2698e-01,  6.5980e-01,
         -5.3338e-01,  1.3397e-01, -9.7840e-01, -1.4174e-01,  4.3269e-01,
         -9.7513e-01,  1.6087e-01, -7.5835e-01,  2.2289e-02,  8.4983e-02,
         -8.7194e-01,  2.0918e-01,  9.9531e-01, -2.4688e-01, -1.6932e-01,
         -2.4345e-01, -9.9964e-01,  1.6744e-01, -8.2719e-01, -2.4693e-01,
         -2.3328e-01, -4.4108e-01,  7.0196e-02,  3.3588e-01,  3.1033e-01,
          3.6946e-01, -1.5520e-01,  6.0225e-02, -1.2864e-01, -5.0064e-01,
         -5.9290e-01,  2.2019e-01, -1.9665e-02, -8.5169e-01, -1.9609e-01,
         -4.7490e-01, -1.2736e-02, -1.

**Extracting_Embeddings_All_Encoder_layers_Of_Bert**


In [26]:
model = BertModel.from_pretrained('bert-base-uncased', output_hidden_states=True)
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

In [27]:
sentence = 'I love Pizza'
tokens = tokenizer.tokenize(sentence)
tokens = ['[CLS]'] + tokens + ['[SEP]']


In [28]:
tokens = tokens + ['[PAD]'] + ['[PAD]']

In [29]:
attention_mask = [1 if i!= '[PAD]' else 0 for i in tokens]

In [30]:
attention_mask

[1, 1, 1, 1, 1, 0, 0]

In [31]:
tokens

['[CLS]', 'i', 'love', 'pizza', '[SEP]', '[PAD]', '[PAD]']

In [32]:
token_ids = tokenizer.convert_tokens_to_ids(tokens)

In [33]:
token_ids

[101, 1045, 2293, 10733, 102, 0, 0]

In [34]:
token_ids = torch.tensor(token_ids).unsqueeze(0)
attention_mask = torch.tensor(attention_mask).unsqueeze(0)

In [35]:
last_hidden_state, pooler_output, hidden_states = model(token_ids, attention_mask = attention_mask)

In [36]:
last_hidden_state.shape

torch.Size([1, 7, 768])

In [37]:
pooler_output.shape

torch.Size([1, 768])

In [38]:
last_hidden_state

tensor([[[ 0.1382,  0.3043,  0.0631,  ..., -0.1041,  0.2224,  0.1510],
         [ 0.3200,  0.2953, -0.1416,  ..., -0.2075,  0.8356,  0.2033],
         [ 1.1893,  0.6508,  0.6801,  ...,  0.1086,  0.4138, -0.2404],
         ...,
         [ 0.6175,  0.1778, -0.0403,  ...,  0.0127, -0.5838, -0.3406],
         [ 0.1496,  0.2934,  0.2243,  ...,  0.2741,  0.2030,  0.0692],
         [ 0.0636,  0.0767,  0.2692,  ...,  0.3536,  0.1529,  0.0537]]],
       grad_fn=<NativeLayerNormBackward>)

In [39]:
pooler_output

tensor([[-8.2725e-01, -2.3180e-01,  4.3839e-01,  5.4852e-01, -1.2203e-01,
         -1.3028e-01,  8.1214e-01,  1.7054e-01,  1.3439e-01, -9.9966e-01,
          1.5789e-01,  2.2010e-01,  9.7317e-01, -2.6980e-01,  9.1344e-01,
         -4.1248e-01,  6.5047e-02, -4.9485e-01,  3.1212e-01, -5.5773e-01,
          5.3245e-01,  8.3556e-01,  5.6662e-01,  2.2098e-01,  3.7355e-01,
          3.8081e-01, -5.0410e-01,  8.9866e-01,  9.2698e-01,  6.5980e-01,
         -5.3338e-01,  1.3397e-01, -9.7840e-01, -1.4174e-01,  4.3269e-01,
         -9.7513e-01,  1.6087e-01, -7.5835e-01,  2.2289e-02,  8.4983e-02,
         -8.7194e-01,  2.0918e-01,  9.9531e-01, -2.4688e-01, -1.6932e-01,
         -2.4345e-01, -9.9964e-01,  1.6744e-01, -8.2719e-01, -2.4693e-01,
         -2.3328e-01, -4.4108e-01,  7.0196e-02,  3.3588e-01,  3.1033e-01,
          3.6946e-01, -1.5520e-01,  6.0225e-02, -1.2864e-01, -5.0064e-01,
         -5.9290e-01,  2.2019e-01, -1.9665e-02, -8.5169e-01, -1.9609e-01,
         -4.7490e-01, -1.2736e-02, -1.

In [40]:
#Here, hidden states contains the representation of all the tokens from the final encoder layer.
len(hidden_states)

13

**BERT for Sentiment Analysis**

In [41]:
pip install nlp==0.4.0

     |████████████████████████████████| 1.7 MB 5.4 MB/s 
     |████████████████████████████████| 212 kB 23.6 MB/s 


In [42]:
from transformers import BertForSequenceClassification, BertTokenizerFast, Trainer, TrainingArguments

In [43]:
from nlp import load_dataset
import torch
import numpy as np

In [44]:
!gdown https://drive.google.com/uc?id=11_M4ootuT7I1G0RlihcC0cA3Elqotlc-
dataset = load_dataset('csv', data_files='./imdbs.csv', split='train')

Downloading...
From: https://drive.google.com/uc?id=11_M4ootuT7I1G0RlihcC0cA3Elqotlc-
To: /content/imdbs.csv
100% 132k/132k [00:00<00:00, 59.8MB/s]


Downloading:   0%|          | 0.00/2.75k [00:00<?, ?B/s]

Using custom data configuration default


0 tables [00:00, ? tables/s]

Dataset csv downloaded and prepared to /root/.cache/huggingface/datasets/csv/default-11046c2826f07a01/0.0.0/ede98314803c971fef04bcee45d660c62f3332e8a74491e0b876106f3d99bd9b. Subsequent calls will reuse this data.


In [45]:
type(dataset)

nlp.arrow_dataset.Dataset

In [46]:
dataset

Dataset(features: {'text': Value(dtype='string', id=None), 'label': Value(dtype='int64', id=None)}, num_rows: 100)

In [47]:
dataset = dataset.train_test_split(test_size=0.3)

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

In [48]:
dataset

{'test': Dataset(features: {'text': Value(dtype='string', id=None), 'label': Value(dtype='int64', id=None)}, num_rows: 30),
 'train': Dataset(features: {'text': Value(dtype='string', id=None), 'label': Value(dtype='int64', id=None)}, num_rows: 70)}

In [49]:
train_set = dataset['train']
test_set = dataset['test']

In [50]:
model = BertForSequenceClassification.from_pretrained('bert-base-uncased')

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForSequenceClassification: ['cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.decoder.weight', 'cls.seq_relationship.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.LayerNorm.bias']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at

In [51]:
tokenizer = BertTokenizerFast.from_pretrained('bert-base-uncased')

Downloading:   0%|          | 0.00/466k [00:00<?, ?B/s]

In [52]:
tokenizer(['I love Paris', 'birds fly', 'snow fall'], padding=True, max_length=5)

{'input_ids': [[101, 1045, 2293, 3000, 102], [101, 5055, 4875, 102, 0], [101, 4586, 2991, 102, 0]], 'token_type_ids': [[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]], 'attention_mask': [[1, 1, 1, 1, 1], [1, 1, 1, 1, 0], [1, 1, 1, 1, 0]]}

In [53]:
def preprocess(data):
  return tokenizer(data['text'], padding=True, truncation=True)

In [54]:
train_set = train_set.map(preprocess, batched=True, batch_size=len(train_set))
test_set = test_set.map(preprocess, batched=True, batch_size=len(test_set))

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

In [55]:
train_set.set_format('torch', columns=['input_ids', 'attention_mask', 'label'])

In [56]:
test_set.set_format('torch', columns=['input_ids', 'attention_mask', 'label'])

In [57]:
train_set

Dataset(features: {'label': Value(dtype='int64', id=None), 'text': Value(dtype='string', id=None), 'input_ids': Sequence(feature=Value(dtype='int64', id=None), length=-1, id=None), 'token_type_ids': Sequence(feature=Value(dtype='int64', id=None), length=-1, id=None), 'attention_mask': Sequence(feature=Value(dtype='int64', id=None), length=-1, id=None)}, num_rows: 70)

In [58]:
batch_size = 8
epochs = 2


In [59]:
warmup_steps = 500
weight_decay = 0.01

In [60]:
training_args = TrainingArguments(
    output_dir='./results',
    num_train_epochs=epochs,
    per_device_train_batch_size=batch_size,
    per_device_eval_batch_size=batch_size,
    warmup_steps=warmup_steps,
    weight_decay=weight_decay,
    evaluate_during_training=True,
    logging_dir='./logs'
)

/usr/local/lib/python3.7/dist-packages/transformers/training_args.py:347: FutureWarning: The `evaluate_during_training` argument is deprecated in favor of `evaluation_strategy` (which has more options)
  FutureWarning,


In [61]:
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_set,
    eval_dataset=test_set
)

In [62]:
trainer.train()

TrainOutput(global_step=18, training_loss=0.8322307268778483)

In [63]:
trainer.evaluate()

{'epoch': 2.0, 'eval_loss': 0.801662266254425}

**Q & A with finetuned BERT**

In [64]:
import torch
from transformers import BertForQuestionAnswering, BertTokenizer

In [67]:
model_1 = BertForQuestionAnswering.from_pretrained('bert-large-uncased-whole-word-masking-finetuned-squad')

Downloading:   0%|          | 0.00/443 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.34G [00:00<?, ?B/s]

In [68]:
tokenizer = BertTokenizer.from_pretrained('bert-large-uncased-whole-word-masking-finetuned-squad')

Downloading:   0%|          | 0.00/232k [00:00<?, ?B/s]

In [69]:
question = "What is the immune system?"
paragraph = "The immune system is a system of many biological structures and processes within an organism that protects against disease."

In [70]:
question = '[CLS]' + question + '[SEP]'
paragraph = paragraph + '[SEP]'

In [71]:
question_tokens = tokenizer.tokenize(question)
paragraph_tokens = tokenizer.tokenize(paragraph)

In [72]:
tokens = question_tokens + paragraph_tokens
input_ids = tokenizer.convert_tokens_to_ids(tokens)

In [73]:
segment_ids = [0] * len(question_tokens)
segment_ids += [1] * len(paragraph_tokens)

In [74]:
segment_ids

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1]

In [75]:
input_ids = torch.tensor([input_ids])
segment_ids = torch.tensor([segment_ids])

In [76]:
input_ids

tensor([[  101,  2054,  2003,  1996, 11311,  2291,  1029,   102,  1996, 11311,
          2291,  2003,  1037,  2291,  1997,  2116,  6897,  5090,  1998,  6194,
          2306,  2019, 15923,  2008, 18227,  2114,  4295,  1012,   102]])

In [77]:
start_scores, end_scores = model_1(input_ids, token_type_ids = segment_ids)

In [79]:
start_scores

tensor([[-5.3344, -4.9339, -6.6966, -5.9976, -5.3169, -8.2161, -8.7843, -5.3343,
          1.7716, -0.8110, -3.7132,  1.3322,  6.7570,  2.6944, -2.5242,  1.3307,
          2.2720, -0.8598, -4.8655, -0.5192, -1.1716, -1.4013, -0.8745, -1.5369,
          1.1904, -3.8364, -1.4591, -5.3340, -5.3329]],
       grad_fn=<SqueezeBackward1>)

In [80]:
start_index = torch.argmax(start_scores)
end_index = torch.argmax(end_scores)

In [81]:
print(' '.join(tokens[start_index:end_index+1]))

a system of many biological structures and processes within an organism that protects against disease
