<a href="https://colab.research.google.com/github/Sonu2252/Abhi/blob/master/Embedding_CountVectorizer_TFIDF_NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
corpus = "The .maketrans() method takes three arguments - the first two are empty strings, and the third is the list of punctuation we want to remove. This tells the function to replace all punctuation with 'None'."


In [ ]:
corpus = corpus.lower()
print(corpus)

the .maketrans() method takes three arguments - the first two are empty strings, and the third is the list of punctuation we want to remove. this tells the function to replace all punctuation with 'none'.


In [ ]:
import re
corpus = re.sub(r'\d+', '', corpus)
print(corpus)

the .maketrans() method takes three arguments - the first two are empty strings, and the third is the list of punctuation we want to remove. this tells the function to replace all punctuation with 'none'.


In [ ]:
import string
corpus = corpus.translate(str.maketrans('', '', string.punctuation))
print(corpus)

the maketrans method takes three arguments  the first two are empty strings and the third is the list of punctuation we want to remove this tells the function to replace all punctuation with none


In [ ]:
corpus = ' '.join([token for token in corpus.split()])
print(corpus)

the maketrans method takes three arguments the first two are empty strings and the third is the list of punctuation we want to remove this tells the function to replace all punctuation with none


In [ ]:
from pprint import pprint
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
nltk.download('punkt')
from nltk.tokenize import word_tokenize
stop_words_nltk = set(stopwords.words('english'))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [ ]:
tokenzied_corpus_nltk = word_tokenize(corpus)
print("Tokenized corpus:", tokenzied_corpus_nltk)
tokenized_corpus_withous_stopwords = [i for i in tokenzied_corpus_nltk if not i in stop_words_nltk]

Tokenized corpus: ['the', 'maketrans', 'method', 'takes', 'three', 'arguments', 'the', 'first', 'two', 'are', 'empty', 'strings', 'and', 'the', 'third', 'is', 'the', 'list', 'of', 'punctuation', 'we', 'want', 'to', 'remove', 'this', 'tells', 'the', 'function', 'to', 'replace', 'all', 'punctuation', 'with', 'none']


In [ ]:
print("Tokenized corpus without sotpwords:", tokenized_corpus_withous_stopwords)

Tokenized corpus without sotpwords: ['maketrans', 'method', 'takes', 'three', 'arguments', 'first', 'two', 'empty', 'strings', 'third', 'list', 'punctuation', 'want', 'remove', 'tells', 'function', 'replace', 'punctuation', 'none']


In [ ]:
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize
stemmer = PorterStemmer()
print("Before Stemming: ")
print(corpus)
print("After stemming: ")
for word in tokenzied_corpus_nltk:
  print(stemmer.stem(word), end=" ")

Before Stemming: 
the maketrans method takes three arguments the first two are empty strings and the third is the list of punctuation we want to remove this tells the function to replace all punctuation with none
After stemming: 
the maketran method take three argument the first two are empti string and the third is the list of punctuat we want to remov thi tell the function to replac all punctuat with none 

In [ ]:
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize
nltk.download('wordnet')
lemmatizer=WordNetLemmatizer()
for word in tokenzied_corpus_nltk:
  print(lemmatizer.lemmatize(word), end=" ")

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
the maketrans method take three argument the first two are empty string and the third is the list of punctuation we want to remove this tell the function to replace all punctuation with none 

In [ ]:
nltk.download('averaged_perceptron_tagger')
print("POS Tagging using NLTK: ")
pprint(nltk.pos_tag(word_tokenize(corpus)))

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
POS Tagging using NLTK: 
[('the', 'DT'),
 ('maketrans', 'NNS'),
 ('method', 'VBP'),
 ('takes', 'VBZ'),
 ('three', 'CD'),
 ('arguments', 'NNS'),
 ('the', 'DT'),
 ('first', 'JJ'),
 ('two', 'CD'),
 ('are', 'VBP'),
 ('empty', 'JJ'),
 ('strings', 'NNS'),
 ('and', 'CC'),
 ('the', 'DT'),
 ('third', 'JJ'),
 ('is', 'VBZ'),
 ('the', 'DT'),
 ('list', 'NN'),
 ('of', 'IN'),
 ('punctuation', 'NN'),
 ('we', 'PRP'),
 ('want', 'VBP'),
 ('to', 'TO'),
 ('remove', 'VB'),
 ('this', 'DT'),
 ('tells', 'VBZ'),
 ('the', 'DT'),
 ('function', 'NN'),
 ('to', 'TO'),
 ('replace', 'VB'),
 ('all', 'DT'),
 ('punctuation', 'NN'),
 ('with', 'IN'),
 ('none', 'NN')]


In [ ]:
documents = ['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']
 

In [ ]:
documents

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [ ]:
p_docs = [doc.lower().replace(".", "") for doc in documents]

In [ ]:
p_docs

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'i am a good boy',
 'i am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [ ]:
voc_size = 10000
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:
one_hot_repr = [one_hot(words, voc_size) for words in p_docs]

In [ ]:
print(one_hot_repr)

[[5836, 1562, 8711, 6337], [5836, 1562, 8711, 6643], [5836, 4040, 8711, 3523], [6750, 8702, 908, 2213, 1591], [6750, 8702, 908, 2213, 6520], [8840, 5836, 1544, 8711, 4304], [3970, 1588, 5495, 2213]]


In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential


In [ ]:
import numpy as np

In [ ]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5836 1562 8711 6337]
 [   0    0    0    0 5836 1562 8711 6643]
 [   0    0    0    0 5836 4040 8711 3523]
 [   0    0    0 6750 8702  908 2213 1591]
 [   0    0    0 6750 8702  908 2213 6520]
 [   0    0    0 8840 5836 1544 8711 4304]
 [   0    0    0    0 3970 1588 5495 2213]]


In [ ]:
dim = 15
model_1 = Sequential([
                Embedding(voc_size, dim, input_length=sent_length)
])

In [ ]:
model_1.compile('adam', 'mse')

In [ ]:
model_1.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 15)             150000    
                                                                 
Total params: 150,000
Trainable params: 150,000
Non-trainable params: 0
_________________________________________________________________


In [ ]:
print(model_1.predict(embedded_docs))

[[[-0.04110805 -0.00079541 -0.03209788  0.0423047  -0.02528633
   -0.04293425 -0.01221649  0.03950367 -0.01736739 -0.04917386
   -0.02897401 -0.02910547  0.02327604 -0.01740768  0.00944523]
  [-0.04110805 -0.00079541 -0.03209788  0.0423047  -0.02528633
   -0.04293425 -0.01221649  0.03950367 -0.01736739 -0.04917386
   -0.02897401 -0.02910547  0.02327604 -0.01740768  0.00944523]
  [-0.04110805 -0.00079541 -0.03209788  0.0423047  -0.02528633
   -0.04293425 -0.01221649  0.03950367 -0.01736739 -0.04917386
   -0.02897401 -0.02910547  0.02327604 -0.01740768  0.00944523]
  [-0.04110805 -0.00079541 -0.03209788  0.0423047  -0.02528633
   -0.04293425 -0.01221649  0.03950367 -0.01736739 -0.04917386
   -0.02897401 -0.02910547  0.02327604 -0.01740768  0.00944523]
  [-0.00556731  0.04109541 -0.02026701 -0.02568579 -0.01361328
    0.03971226 -0.02542874  0.0067512  -0.01915748 -0.01250161
    0.01725284 -0.00241263  0.02954283  0.04115875  0.01474083]
  [ 0.04876533  0.00768006  0.00874338 -0.04306697

In [ ]:
embedded_docs[0]

array([   0,    0,    0,    0, 5836, 1562, 8711, 6337], dtype=int32)

In [ ]:
print(model_1.predict(embedded_docs[0]))

[[-0.04110805 -0.00079541 -0.03209788  0.0423047  -0.02528633 -0.04293425
  -0.01221649  0.03950367 -0.01736739 -0.04917386 -0.02897401 -0.02910547
   0.02327604 -0.01740768  0.00944523]
 [-0.04110805 -0.00079541 -0.03209788  0.0423047  -0.02528633 -0.04293425
  -0.01221649  0.03950367 -0.01736739 -0.04917386 -0.02897401 -0.02910547
   0.02327604 -0.01740768  0.00944523]
 [-0.04110805 -0.00079541 -0.03209788  0.0423047  -0.02528633 -0.04293425
  -0.01221649  0.03950367 -0.01736739 -0.04917386 -0.02897401 -0.02910547
   0.02327604 -0.01740768  0.00944523]
 [-0.04110805 -0.00079541 -0.03209788  0.0423047  -0.02528633 -0.04293425
  -0.01221649  0.03950367 -0.01736739 -0.04917386 -0.02897401 -0.02910547
   0.02327604 -0.01740768  0.00944523]
 [-0.00556731  0.04109541 -0.02026701 -0.02568579 -0.01361328  0.03971226
  -0.02542874  0.0067512  -0.01915748 -0.01250161  0.01725284 -0.00241263
   0.02954283  0.04115875  0.01474083]
 [ 0.04876533  0.00768006  0.00874338 -0.04306697 -0.03192484 -0.

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
print("Our corpus: ", p_docs)

Our corpus:  ['the glass of milk', 'the glass of juice', 'the cup of tea', 'i am a good boy', 'i am a good developer', 'understand the meaning of words', 'your videos are good']


In [ ]:
count_vect = CountVectorizer()
bow_rep = count_vect.fit_transform(p_docs)
print("Our vocabulary: ", count_vect.vocabulary_)
print("BoW representation for 'dog bites man': ", bow_rep[0].toarray())
print("BoW representation for 'man bites dog': ", bow_rep[1].toarray())

Our vocabulary:  {'the': 12, 'glass': 5, 'of': 10, 'milk': 9, 'juice': 7, 'cup': 3, 'tea': 11, 'am': 0, 'good': 6, 'boy': 2, 'developer': 4, 'understand': 13, 'meaning': 8, 'words': 15, 'your': 16, 'videos': 14, 'are': 1}
BoW representation for 'dog bites man':  [[0 0 0 0 0 1 0 0 0 1 1 0 1 0 0 0 0]]
BoW representation for 'man bites dog':  [[0 0 0 0 0 1 0 1 0 0 1 0 1 0 0 0 0]]


In [ ]:
temp = count_vect.transform(['dog and man are best friends'])
print("BoW representation for 'dog and man are best friends': ", temp.toarray())

BoW representation for 'dog and man are best friends':  [[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()
bow_rep_tfidf = tfidf.fit_transform(p_docs)
print("TFIDF representation for all the documents in corpus\n", bow_rep_tfidf.toarray())

TFIDF representation for all the documents in corpus
 [[0.         0.         0.         0.         0.         0.53053875
  0.         0.         0.         0.63913718 0.3937209  0.
  0.3937209  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.53053875
  0.         0.63913718 0.         0.         0.3937209  0.
  0.3937209  0.         0.         0.         0.        ]
 [0.         0.         0.         0.60204273 0.         0.
  0.         0.         0.         0.         0.37087    0.60204273
  0.37087    0.         0.         0.         0.        ]
 [0.56060334 0.         0.67535583 0.         0.         0.
  0.47918515 0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.        ]
 [0.56060334 0.         0.         0.         0.67535583 0.
  0.47918515 0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.        ]
 [0.         0.         0.      

In [ ]:
import gensim
import pandas as pd
